name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: PlaywriteMXGuides
      fonts:
        - asset: fonts/PlaywriteMXGuides-Regular.ttf
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf